name: 'Deploy PR Preview to Caddy Server'
description: 'Builds and deploys a PR preview to a Caddy server with dynamic subdomains.'
inputs:
  action:
    description: 'Action to perform: "deploy" or "cleanup"'
    required: true
    default: 'deploy'
  ssh_host:
    description: 'SSH Host'
    required: true
  ssh_user:
    description: 'SSH User'
    required: true
  ssh_private_key:
    description: 'SSH Private Key'
    required: true
  ssh_password:
    description: 'SSH Private Key Password'
    required: false
  project_name:
    description: 'Name of the project (used in URL and folder path)'
    required: true
  build_command:
    description: 'Command to build the application (e.g., "npm run build")'
    required: false
  dist_dir:
    description: 'Directory containing build artifacts (e.g., "dist/my-app")'
    required: false
  domain_suffix:
    description: 'Domain suffix for the preview URL'
    required: false
    default: 'github.klinki.cz'

outputs:
  preview_url:
    description: 'The URL of the deployed preview'
    value: ${{ steps.set-url.outputs.url }}

runs:
  using: "composite"
  steps:
    - name: Setup SSH Key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ inputs.ssh_private_key }}
        passphrase: ${{ inputs.ssh_password }}
        known_hosts: unnecessary
        if_key_exists: replace

    - name: Build Application
      if: inputs.action == 'deploy' && inputs.build_command != ''
      shell: bash
      run: ${{ inputs.build_command }}

    - name: Deploy to Server
      if: inputs.action == 'deploy'
      shell: bash
      env:
        PR_NUMBER: ${{ github.event.number }}
        SSH_HOST: ${{ inputs.ssh_host }}
        SSH_USER: ${{ inputs.ssh_user }}
        PROJECT_NAME: ${{ inputs.project_name }}
        DIST_DIR: ${{ inputs.dist_dir }}
      run: |
        PR_ID="pr-${PR_NUMBER}"
        TARGET_DIR="/var/www/$PROJECT_NAME/$PR_ID"

        echo "Deploying to $TARGET_DIR on $SSH_HOST..."

        # Create directory
        ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST "mkdir -p $TARGET_DIR"

        # Clean directory
        ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST "rm -rf $TARGET_DIR/*"

        # Copy files
        scp -o StrictHostKeyChecking=no -r $DIST_DIR/* $SSH_USER@$SSH_HOST:$TARGET_DIR

    - name: Cleanup Deployment
      if: inputs.action == 'cleanup'
      shell: bash
      env:
        PR_NUMBER: ${{ github.event.number }}
        SSH_HOST: ${{ inputs.ssh_host }}
        SSH_USER: ${{ inputs.ssh_user }}
        PROJECT_NAME: ${{ inputs.project_name }}
      run: |
        PR_ID="pr-${PR_NUMBER}"
        TARGET_DIR="/var/www/$PROJECT_NAME/$PR_ID"

        echo "Removing $TARGET_DIR on $SSH_HOST..."
        ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST "rm -rf $TARGET_DIR"

    - name: Set Output URL
      id: set-url
      if: inputs.action == 'deploy'
      shell: bash
      env:
        PR_NUMBER: ${{ github.event.number }}
        PROJECT_NAME: ${{ inputs.project_name }}
        DOMAIN_SUFFIX: ${{ inputs.domain_suffix }}
      run: |
        URL="https://pr-${PR_NUMBER}.${PROJECT_NAME}.${DOMAIN_SUFFIX}"
        echo "url=$URL" >> $GITHUB_OUTPUT
