import { existsSync, readFileSync, statSync, writeFileSync } from 'fs';
import { resolve, join } from 'path';

const args = process.argv.slice(2);

function findGitDir(basePath) {
  const dotGitPath = join(basePath, '.git');

  if (!existsSync(dotGitPath)) {
    throw new Error(`Unable to find .git directory from ${basePath}`);
  }

  const dotGitStat = statSync(dotGitPath);
  if (dotGitStat.isDirectory()) {
    return dotGitPath;
  }

  const gitFile = readFileSync(dotGitPath, 'utf8').trim();
  const match = gitFile.match(/^gitdir:\s*(.+)$/i);

  if (!match) {
    throw new Error(`Unable to resolve git dir from ${dotGitPath}`);
  }

  return resolve(basePath, match[1].trim());
}

function readPackedRef(gitDir, ref) {
  const packedRefsPath = join(gitDir, 'packed-refs');

  if (!existsSync(packedRefsPath)) {
    return null;
  }

  const lines = readFileSync(packedRefsPath, 'utf8').split(/\r?\n/);

  for (const line of lines) {
    if (!line || line.startsWith('#') || line.startsWith('^')) {
      continue;
    }

    const [sha, packedRef] = line.split(' ');
    if (packedRef === ref) {
      return sha;
    }
  }

  return null;
}

function readRefSha(gitDir, ref) {
  const refPath = join(gitDir, ref);

  if (existsSync(refPath)) {
    return readFileSync(refPath, 'utf8').trim();
  }

  const packedSha = readPackedRef(gitDir, ref);
  if (packedSha) {
    return packedSha;
  }

  throw new Error(`Unable to resolve git ref ${ref}`);
}

function getGitInfo(basePath) {
  const gitDir = findGitDir(basePath);
  const headPath = join(gitDir, 'HEAD');
  const head = readFileSync(headPath, 'utf8').trim();

  if (!head.startsWith('ref: ')) {
    return {
      fullRevision: head,
      revision: head.slice(0, 7),
      branch: 'detached',
    };
  }

  const ref = head.slice(5).trim();
  const fullRevision = readRefSha(gitDir, ref);
  const branch = ref.startsWith('refs/heads/') ? ref.slice('refs/heads/'.length) : ref;

  return {
    fullRevision,
    revision: fullRevision.slice(0, 7),
    branch,
  };
}

function createVersionsFile(filename, version, gitInfo) {
  console.log(`version: '${version}', revision: '${gitInfo.revision}', branch: '${gitInfo.branch}'`);

  const content =
    `// this file is automatically generated by git-version.mjs script
export const versions = {
  version: '${version}',
  revision: '${gitInfo.revision}',
  commitHash: '${gitInfo.fullRevision}',
  branch: '${gitInfo.branch}',
  date: '${new Date().toISOString()}',
};
`;

  writeFileSync(filename, content, { encoding: 'utf8' });
}

const basePath = resolve(args[0] || '.');
const version = process.env['npm_package_version'] || '0.0.0';
const gitInfo = getGitInfo(basePath);

createVersionsFile(join(basePath, 'src/environments/version.ts'), version, gitInfo);
